config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :requests do
    get "calendar", to: "requests#calendar", on: :member
    resources :exchanges, only: %i[new create]
  end
  resources :exchanges, except: %i[new create]
  resources :companies
  resources :orders, only: [:show, :create]
  resources :memberships, only: [:show, :index]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer flex-container">
  <div class="footer-links ">
    <a href="https://github.com/raquelciusz/my-shift/wiki" target="_frame"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Website made with <i class="fas fa-heart"></i> by My Shift
  </div>
</div>

app/views/shared/_home-navbar.html.erb
  <nav>
    <div class="d-flex justify-content-between align-items-center">
      <div>
        <ul class="menuItems">
          <a class="navbar-brand justify-content" href="#">
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" width="40px" height="40px" /></a>
          <li><a href='#' data-item='Home'>Home</a></li>
          <li><a href='#' data-item='About'>About</a></li>
          <li><a href='#' data-item='Projects'>Projects</a></li>
          <li><a href='#' data-item='Blog'>Blog</a></li>
          <li><a href='#' data-item='Contact'>Contact</a></li>
        </ul>
      </div>
      <div>
        <%= link_to "Login", "#", class: "btn btn-ghost mx-3" %>
      </div>
    </div>

  </nav>

app/views/shared/_modal-turbo.html.erb
<%= turbo_frame_tag "modal" do %>
  <div id="editTitleModal" data-controller="modal-turbo" data-turbo="true">
    <div class="transparent-overlay modal-inside-card" data-action="click->modal-turbo#closeModal"></div>
    <%= turbo_frame_tag "modal-body" do %>
      <i class="fas fa-times modal-close-button" data-action="click->modal-turbo#closeModal"></i>
      <div class="modal-card">
        <i class="fas fa-times modal-close-button" data-action= "click->modal-turbo#closeModal" data-modal-layer= 'editTitleModal'></i>
        <%= yield %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container-fluid justify-content-between">
      <ul class="menuItems">
        <a class="navbar-brand justify-content" href="/#">
        <%= image_tag 'logo-myshift-plane.png', width: "45px", height: "40px", class: 'logo-nav' %></a>
        <% if !user_signed_in? %>
          <li><a href='/' data-item='Início'>Início</a></li>
          <li><a href='/#sobre' data-item='Sobre'>Sobre</a></li>
          <li><a href='mailto:contato@myshift.com.br' data-item='Contato'>Contato</a></li>
        <% end %>
      </ul>
  </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <div class="d-flex align-items-center">
            <%= link_to '', new_request_path, class: "fa-regular fa-calendar-plus navbar-icons", data: { turbo: true, turbo_frame: "modal"} %>
            <%= link_to '', requests_path, class: "fa-solid fa-list-ul navbar-icons", data: { turbo: true, turbo_frame: "modal"} %>
          </div>
          <li class="nav-item dropdown">
            <% if current_user.avatar.attached? %>
                <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle avatar-navbar", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://i1.sndcdn.com/avatars-000255771415-dx5rag-t200x200.jpg", class: "avatar dropdown-toggle border border-white", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Feed", requests_path, class: "dropdown-item" %>
              <%= link_to "Minhas trocas", exchanges_path, class: "dropdown-item" %>
              <%= link_to "Meu perfil", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Sair", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "", new_user_session_path, class: "fa-solid fa-arrow-right-to-bracket navbar-icons" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  </div>
</div>