config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :requests do
    get "calendar", to: "requests#calendar", on: :member
    resources :exchanges, only: %i[new create]
  end
  resources :exchanges, except: %i[new create]
  resources :companies
  resources :orders, only: [:show, :create]
  resources :memberships, only: [:show, :index]
end

app/models/request.rb
class Request < ApplicationRecord
  # include PgSearch::Model

  belongs_to :user
  has_one :exchange, dependent: :destroy

  validates :origin, presence: true
  validates :destination, presence: true

  REQUEST_TYPE = ["Folgar", "Trocar", "Trabalhar"]
  validates :request_type, presence: true
  validates :request_type, inclusion: { in: REQUEST_TYPE }

  validates :start_time, :end_time, presence: true
  validate :end_time_after_start_time

  private


  def end_time_after_start_time
    return if end_time.blank? || start_time.blank?

    if end_time < start_time
      errors.add(:end_time, "Data inválida! Deve ser maior que a data da ida.")
    end
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: %i[show edit update destroy calendar]

  def index
    @requests_all = policy_scope(Request)
    @exchanges = Exchange.where(status: "Pendente")
    @requests = @requests_all.where.missing(:exchange).order(created_at: :desc)

    if params[:start_time].present? || params[:end_time].present?
      start_time = params[:start_time].blank? ? Date.new(1980, 1, 1) : Time.zone.parse(params[:start_time]).beginning_of_day
      end_time = params[:end_time].blank? ? Date.new(2040, 1, 1) : Time.zone.parse(params[:end_time]).end_of_day

      @requests = @requests.where(start_time: start_time..end_time, end_time: start_time..end_time)
    end

    # if params[:start_time].present? || params[:end_time].present?
    #   start_time = params[:start_time].blank? ? Date.new(1980, 1, 1)..Date.new(2040, 1, 1) : (Time.zone.parse(params[:start_time]).beginning_of_day)..(Time.zone.parse(params[:start_time]).beginning_of_day + 1.day)
    #   end_time = params[:end_time].blank? ? Date.new(1980, 1, 1)..Date.new(2040, 1, 1) : (Time.zone.parse(params[:end_time]).end_of_day - 1.day)..(Time.zone.parse(params[:end_time]).end_of_day)

    #   @requests = @requests.where(start_time: start_time, end_time: end_time)
    # end

    if params[:origin].present?
      @requests = @requests.where("origin ILIKE ?", "%#{params[:origin]}%")
    end

    if params[:destination].present?
      @requests = @requests.where("destination ILIKE ?", "%#{params[:destination]}%")
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: "mycalendar", locals: { request: @request }, formats: [:html] }
    end
  end

  def search
    start_time = params[:start_time] || DateTime.now
    end_time = params[:end_time] || DateTime.now
    origin = params[:origin]
    destination = params[:destination]
    @requests = Request.search(start_time, end_time, origin, destination)
  end

  def show
    @exchanges = @request.exchange
    @exchange = Exchange.new
  end

  def new
    @request = Request.new
    authorize @request
  end

  def update
    authorize @request
    if @request.update(request_params)
      redirect_to requests_path, notice: "Sua solicitação foi alterada com sucesso."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @request.destroy
    redirect_to requests_path, status: :see_other, notice: "Sua solicitação foi excluída."
  end

  def create
    @request = Request.new(request_params)
    @request.user = current_user

    # se usuario criou request com mesma origem block
    # if @request.user.includes() ja tem @request mesmo origem

    # se usuario criou request com mesmo data block

    # se usuario criou request com mesmo horario block


    authorize @request
    range = params[:request][:start_time].split(' to ')
    @request.start_time = range.first
    @request.end_time = range.last
    # current_user
    if @request.save
      mail = RequestMailer.with(request: @request).newRequest
      mail.deliver_now
      redirect_to requests_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def calendar
    respond_to do |format|
      format.text {  render partial: 'requests/mycalendar', locals: { requests: [@request] }, formats: [:html] }
    end
  end

  private

  def set_request
    @request = Request.find(params[:id])
    authorize @request
  end

  def request_params
    params.require(:request).permit(:request_type, :start_time, :end_time, :origin, :destination, :available, :user_id)
  end
end

app/views/requests/_mycalendar.html.erb
<%= month_calendar(events: requests, end_attribute: :end_time) do |date, reqs| %>
  <%= date.day %>
  <% reqs.each do |request| %>
    <div class="meeting">
      <% if date == request.start_time.to_date  %>
        <%= request.origin %>
        <%= request.start_time.strftime("%H:%M") %>
      <% end %>
      <% if date == request.end_time.to_date  %>
        <%= request.destination %>
        <%= request.end_time.strftime("%H:%M") %>
      <% end  %>
    </div>
  <% end %>
<% end %>

app/views/requests/create.html.erb
<h1>Requests#create</h1>
<p>Find me in app/views/requests/create.html.erb</p>

app/views/requests/destroy.html.erb
<%= render "shared/modal-turbo" do %>
  <%= simple_form_for @request, html: { class: "mt-3", data: { turbo: true, turbo_frame: 'modal' } } do |f| %>
    <h5>Tem certeza que gostaria de deletar requisição?</h5>
    <%= f.submit class: "btn-capsule-sm btn-outline-gold mt-3" %>
  <% end %>
<% end %>

app/views/requests/edit.html.erb
<%= render "shared/modal-turbo" do %>
  <%= simple_form_for @request, html: { class: "mt-3", data: { turbo: true, turbo_frame: 'modal' } } do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="d-flex justify-content-around mt-5 mb-5" id="form-bg">
      <div>
          <%= f.input :request_type, as: :select, class: "chosen-select", collection: Request::REQUEST_TYPE, prompt: 'Selecione', label: 'Tipo de requisição' %>
          <%= f.input :start_time, label: 'Ida', as: :string, input_html: { type: 'datetime-local', value: (@request.start_time.strftime('%Y-%m-%dT%H:%M')) } %>
          <%= f.input :end_time, label: 'Volta',  as: :string,  input_html: { type: 'datetime-local', value: (@request.end_time.strftime('%Y-%m-%dT%H:%M')) } %>
          <%= f.input :origin, placeholder: 'São Paulo', label: 'Origem' %>
          <%= f.input :destination, placeholder: 'Rio de Janeiro', label: 'Destino' %>
          <%= f.submit class: 'btn btn-primary hover:text-primary rounded-pill shadow-sm border px-4', input_html: { data: { 'flatpickr-target': "btnSubmit" } }%>
      </div>
    </div>
  <% end %>
<% end %>

app/views/requests/index.html.erb
<div data-controller="open-calendar" class="mt-5">
  <div id="form-bg">
    <%= form_with url: requests_path, method: :get, class: "d-flex", data: { controller: 'flatpickr-search' } do |f| %>
      <div id="ida">
        <%= text_field_tag :start_time, params[:start_time], data: { 'flatpickr-search-target': "startTime" }, placeholder: "Ida" %>
      </div>
      <div id="volta">
        <%= text_field_tag :end_time, params[:end_time], data: { 'flatpickr-search-target': "endTime" }, placeholder: "Volta" %>
      </div>
      <div id="origem" data-controller="cities" data-cities-key-value="<%= ENV["MAPBOX_KEY"] %>" data-cities-placeholder-value="Origem">
        <%= text_field_tag :origin, params[:origin], placeholder: "Origem", data: { cities_target: "input" }, class: "d-none" %>
      </div>
      <div id="destino" data-controller="cities" data-cities-key-value="<%= ENV["MAPBOX_KEY"] %>" data-cities-placeholder-value="Destino">
        <%= text_field_tag :destination, params[:destination], placeholder: "Destino", data: { cities_target: "input" }, class: "d-none" %>
      </div>
      <div id="pesquisar">
        <%= button_tag type: 'submit', class: "btn-main", id: "register-button" do %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="container">
    <div class="request_card_total">

      <!-- DIV relacionada a exchange -->
      <% @exchanges.each do |exchange| %>
        <% if exchange.request.user == current_user %>
          <div class="request_card bg-secondary bg-gradient order1">
            <div>
              <div class="bg-primary bg-gradient text-white text-center py-1 mb-3 rounded-3" style="width: 100px"><strong><%= exchange.status.upcase %></strong></div>
              <h5 class="mb-3">Você pediu para<strong> <%= exchange.request.request_type %></strong></h5>
              <p> <i class="fa-regular fa-calendar"></i> <%= l exchange.request.start_time, format: :short %> <i class="fa-solid fa-arrow-right"></i> <%= l exchange.request.end_time, format: :short %> </p>
              <p> <i class="fa-solid fa-location-dot"></i> <%= exchange.request.origin %> <i class="fa-solid fa-arrow-right"></i> <%= exchange.request.destination %> </p>
              <%= link_to "", exchange_path(exchange), class: "fa-solid fa-check h5 text-decoration-none d-inline-flex text-success border border-success text-center rounded-3 px-3 py-2 mt-3 link-primary", data: { turbo: true, turbo_method: :patch, turbo_confirm: "Confirmar?"} %>
              <%= link_to "", exchange_path(exchange), class: "fa-solid fa-x h5 text-decoration-none text-danger d-inline-flex border border-danger text-center rounded-3 px-3 py-2 link-primary", data: { turbo: true, turbo_method: :delete, turbo_confirm: "Recusar?"} %>
            </div>
            <div>
              <label class="btn avatar-photo">
                <% if exchange.user.avatar.attached? %>
                  <%= cl_image_tag exchange.user.avatar.key %>
                <% else %>
                  <%= image_tag "https://i1.sndcdn.com/avatars-000255771415-dx5rag-t200x200.jpg"%>
                <% end %>
              </label>
              <p> <i class="fa-solid fa-user"></i> <%= exchange.user.first_name.capitalize %> pegou sua requisição </p>
            </div>
          </div>
        <% elsif exchange.user == current_user %>
          <div class="request_card order2">
            <div>
              <div class="text-white bg-warning bg-gradient text-center py-1 mb-2 rounded-3" style="width: 100px"><strong>AGUARDE</strong></div>
              <% if exchange.request.request_type == "Folgar" %>
                <h5 class="mt-3 mb-3"> Você pediu para trabalhar no lugar de <%= exchange.request.user.first_name.capitalize %> </h5>
              <% elsif exchange.request.request_type == "Trabalhar" %>
                <h5 class="mt-3 mb-3"> Você cedeu dias de trabalho para <%= exchange.request.user.first_name.capitalize %> </h5>
              <% else exchange.request.request_type == "Trocar" %>
                <h5 class="mt-3 mb-3"> Você quer trocar com <%= exchange.request.user.first_name.capitalize %> </h5>
              <% end %>
              <p> <i class="fa-regular fa-calendar"></i> <%= l exchange.request.start_time, format: :short %> <i class="fa-solid fa-arrow-right"></i> <%= l exchange.request.end_time, format: :short %> </p>
              <p> <i class="fa-solid fa-location-dot"></i> <%= exchange.request.origin %> <i class="fa-solid fa-arrow-right"></i> <%= exchange.request.destination %> </p>
              <%= link_to "", exchange_path(exchange), class: "fa-solid fa-trash-can index-icons text-decoration-none mt-3", data: { turbo: true, turbo_method: :delete, turbo_confirm: "Deletar?"} %>
            </div>
            <div>
              <label class="btn avatar-photo">
                <% if exchange.request.user.avatar.attached? %>
                  <%= cl_image_tag exchange.request.user.avatar.key %>
                <% else %>
                  <%= image_tag "https://i1.sndcdn.com/avatars-000255771415-dx5rag-t200x200.jpg"%>
                <% end %>
              </label>
              <p><i class="fa-solid fa-user"></i> <strong><%= exchange.request.user.first_name.capitalize %></strong> precisa aprovar!</p>
            </div>
          </div>
        <% end %>
      <% end %>
      <!-- DIV relacionada a exchange -->

      <!-- DIV relacionada a request -->
      <% @requests.each do |request| %>
        <div class="request_card order3">
          <div>
              <p><%= request.exchange.present? ? "Já em negociação" : "Disponível" unless request.user == current_user %></p>
              <h3>  <% if request.request_type == "Folgar" && request.user == current_user %> </h3>
                    <h3> Quer trabalhar? </h3>
                    <% elsif request.request_type == "Trabalhar" %>
                    <h3> Quer Folgar? </h3>
                    <% else request.request_type == "Trocar" %>
                    <h3> Quer trocar? </h3>
                    <% end %>
              <p> <i class="fa-regular fa-calendar"></i> <%= l request.start_time, format: :short %> <i class="fa-solid fa-arrow-right"></i> <%= l request.end_time, format: :short %> </p>
              <p> <i class="fa-solid fa-location-dot"></i> <%= request.origin %> <i class="fa-solid fa-arrow-right"></i> <%= request.destination %> </p>
              <p> <i class="fa-regular fa-clock"></i> <%= request.created_at.strftime("%d %b %y") %> </p>
              <p> <%= request.user.company.name %></p>

              <div class="d-flex gap-3 mt-3">
                <%= link_to "Quero esta chave", request_path(request), :class => "btn btn-main", data: { turbo: true, turbo_frame: "modal" } unless request.user == current_user %>
                <%=  link_to "", edit_request_path(request), class: "fa-solid fa-pen-to-square index-icons text-decoration-none", data: { turbo: true, turbo_frame: "modal"} if policy(request).edit?%>
                <%= link_to "", request, class: "fa-solid fa-trash-can index-icons text-decoration-none", data: { turbo: true, turbo_method: :delete, turbo_confirm: "Cancelar requisição?", turbo_frame: "modal"} if policy(request).destroy? %>
                <button type="button" class="btn btn-calendar" data-action="click->open-calendar#open" data-open-calendar-id-param='<%= request.id %>'>
                <i class="fa-solid fa-calendar-days"></i>
                </button>
              </div>
          </div>
          <div>
            <label class="btn avatar-photo">
              <% if request.user.avatar.attached? %>
                <%= cl_image_tag request.user.avatar.key %>
              <% else %>
                <%= image_tag "https://i1.sndcdn.com/avatars-000255771415-dx5rag-t200x200.jpg"%>
              <% end %>
            </label>
            <p> <i class="fa-solid fa-user"></i> <%= request.user.first_name.capitalize %> quer <%= request.request_type %> </p>
          </div>

        </div>
        <% end %>
      </div>
      <!-- DIV relacionada a request -->

      <% if @requests.count.zero?  %>
        <h3 class="my-3 mx-5"> Nenhum pedido encontrado. </h3>
      <% end %>

    <!-- Modal -->
    <div class="modal modal-lg fade" data-open-calendar-target='modal' tabindex="-1">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Calendário</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body" data-open-calendar-target='modalBody'>
          </div>
          <div class="modal-footer">
            <p class="px-3 py-3 mb-0">Destacado em verde as datas selecionadas.</p>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <!-- Modal -->

  </div>
</div>

app/views/requests/new.html.erb
<%= render "shared/modal-turbo" do %>
  <%= simple_form_for @request, html: { class: "mt-3", data: { controller: 'flatpickr', turbo: true, turbo_frame: 'modal' } } do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <p class="modal-title">Solicitação</p>
    <hr>
    <div class="d-flex justify-content-center" id="form-bg">
      <div>
          <%= f.input :request_type, as: :select, class: "chosen-select", collection: Request::REQUEST_TYPE, prompt: 'Selecione', label: 'Tipo de requisição', error: false %>
          <%= f.input :start_time, placeholder: '00-00-0000', label: 'Ida', as: :string, input_html: { data: { 'flatpickr-target': "startTime" } }, error: false  %>
          <%= f.input :end_time, placeholder: '00-00-0000', label: 'Volta', as: :string, input_html: { data: { 'flatpickr-target': "endTime" } }, error: false  %>
          <%= f.input :origin, placeholder: "Origem", label: 'Origem', input_html: { data: { 'cities-target': 'input' }, class: "d-none" }, wrapper_html: { data: {controller: "cities", cities_key_value: ENV["MAPBOX_KEY"]}}, error: "Campo em branco"  %>
          <%= f.input :destination, placeholder: "Destino", label: 'Destino', input_html: { data: { 'cities-target': 'input' }, class: "d-none border" }, wrapper_html: { data: {controller: "cities", cities_key_value: ENV["MAPBOX_KEY"]}}, error: "Campo em branco" %>
          <%= f.submit 'Confirmar', class: 'btn btn-primary hover:text-primary rounded-pill shadow-sm border px-4', input_html: { data: { 'flatpickr-target': "btnSubmit" } }%>
      </div>
    </div>
  <% end %>
<% end %>

app/views/requests/show.html.erb
<%= render "shared/modal-turbo" do %>
  <div class="d-flex flex-column align-items-center">
    <div class="justify-text-center align-center">
      <div class="text-white bg-warning bg-gradient text-center py-1 mb-2 rounded-3" style="width: 100px">
        <strong>AGUARDE</strong>
      </div>
      <% if @request.request_type == "Folgar" %>
        <h5 class="mt-3"> Você pediu para trabalhar no lugar de <strong><%= @request.user.first_name.capitalize %></strong> </h5>
      <% elsif @request.request_type == "Trabalhar" %>
        <h5 class="mt-3"> Você cedeu dias de trabalho para <%= @request.user.first_name.capitalize %> </h5>
      <% else @request.request_type == "Trocar" %>
        <h5 class="mt-3"> Você quer trocar com <%= @request.user.first_name.capitalize %> </h5>
      <% end %>
      <div class="bg-secondary bg-gradient p-3 mb-2 rounded-3 request_card">
        <p> <i class="fa-regular fa-calendar"></i> <%= l @request.start_time, format: :short %> <i class="fa-solid fa-arrow-right"></i> <%= l @request.end_time, format: :short %> </p> |
        <p> <i class="fa-solid fa-location-dot"></i> <%= @request.origin %> <i class="fa-solid fa-arrow-right"></i> <%= @request.destination %> </p>
      </div>
    </div>

    <div class="justify-text-center align-center gap-2">
      <label class="btn avatar-photo">
        <% if @request.user.avatar.attached? %>
          <%= cl_image_tag @request.user.avatar.key %>
        <% else %>
          <%= image_tag "https://i1.sndcdn.com/avatars-000255771415-dx5rag-t200x200.jpg"%>
        <% end %>
      </label>
      <p class="text-center"><i class="fa-solid fa-user"></i> <strong><%= @request.user.first_name.capitalize %></strong> precisa aprovar!</p>
    </div>
  </div>
  <%= simple_form_for [@request, @exchange], html: { class: "mt-3", data: { turbo: true } } do |f| %>
    <div class="text-center">
      <%= f.submit 'Confirmar', class: "btn-main", data: { turbo: true, turbo_frame: "modal" } %>
    </div>
  <% end %>
<% end %>

app/views/requests/update.html.erb
<h1>Requests#update</h1>
<p>Find me in app/views/requests/update.html.erb</p>